description: >
  CircleCI base executor.
docker:
  - image: "cimg/base:<<parameters.tag>>"
parameters:
  tag:
    default: stable
    description: >
      Pick a specific cimg/base image variant:
      https://hub.docker.com/r/cimg/base/tags
    type: string
